export const USER_SAVE = "USER_SAVE";

export const CUSTOMERS_SAVE = "CUSTOMERS_SAVE";

export const PROVINCES_SAVE = "PROVINCES_SAVE";

export const CITIES_SAVE = "CITIES_SAVE";

export const DISTRICTS_SAVE = "DISTRICTS_SAVE";

export const PRODUCTS_SAVE = "PRODUCTS_SAVE";

export const CATEGORIES_SAVE = "CATEGORIES_SAVE";

export const INFORMATIONS_SAVE = "INFORMATIONS_SAVE";

export const HEADING_SAVE = "HEADING_SAVE";

export const PAYMENTS_SAVE = "PAYMENTS_SAVE";

export const ACCOUNTS_SAVE = "ACCOUNTS_SAVE";

export const SHIPMENT_TIME_SAVE = "SHIPMENT_TIME_SAVE";

export const COVERAGE_AREA_SAVE = "COVERAGE_AREA_SAVE";

export const ORDERS_SAVE = "ORDERS_SAVE";
export const ORDERS_ADD = "ORDERS_ADD";

export const CARTS_ADD = "CARTS_ADD";
export const CARTS_CHANGE_QUANTITY = "CARTS_CHANGE_QUANTITY";
export const CARTS_CHANGE_BUYER = "CARTS_CHANGE_BUYER";
export const CARTS_REMOVE = "CARTS_REMOVE";
export const CARTS_RESET = "CARTS_RESET";

export const LOADING_SET = "LOADING_SET";

export const ALERT_SET = "ALERT_SET";
